run_analysis <- function(){
  library(plyr)
  xtest <- read.table("data\\UCI HAR Dataset\\test\\x_test.txt")
  ytest <- read.table("data\\UCI HAR Dataset\\test\\y_test.txt")
  subtest <- read.table("data\\UCI HAR Dataset\\test\\subject_test.txt")
  xtrain <- read.table("data\\UCI HAR Dataset\\train\\x_train.txt")
  ytrain <- read.table("data\\UCI HAR Dataset\\train\\y_train.txt")
  subtrain <- read.table("data\\UCI HAR Dataset\\train\\subject_train.txt")
  sub<-rbind(subtrain,subtest)
  act <- rbind(ytrain,ytest)
  act$V1 <- sub("1","WALKING",act$V1)
  act$V1 <- sub("2","WALKING UPSTAIRS",act$V1)
  act$V1 <- sub("3","WALKING DOWNSTAIRS",act$V1)
  act$V1 <- sub("4","SITTING",act$V1)
  act$V1 <- sub("5","STANDING",act$V1)
  act$V1 <- sub("6","LAYING",act$V1)
  meanstd <-rbind(xtrain,xtest)
  feat <- read.table("data\\UCI HAR Dataset\\features.txt")
  f <-as.character(feat[1:561,2])
  colnames(meanstd) <- c(f)
  meanstd<-meanstd[grep("mean|std",names(meanstd))]
  names(meanstd)<-sub("^t","time",names(meanstd),)
  names(meanstd)<-gsub("-","",names(meanstd),)
  names(meanstd)<-sub("\\(\\)","",names(meanstd),)
  names(meanstd)<-sub("^f","freq",names(meanstd),)
  names(meanstd)<-sub("mean","Mean",names(meanstd),)
  names(meanstd)<-sub("std","StdDev",names(meanstd),)
  names(meanstd)<-sub("BodyBody","Body",names(meanstd),)
  meanstd <- cbind(sub,meanstd)
  names(meanstd)<-sub("V1","Subject",names(meanstd),)
  meanstd$Subject <-as.factor(meanstd$Subject)
  meanstd <- cbind(act,meanstd)
  names(meanstd)<-sub("V1","Activity",names(meanstd),)
  M<-ddply(meanstd, .(Subject,Activity), numcolwise(mean))
  return(M)
}
